### ISSUE TITLE
Release Alpha Milestone

### ISSUE THREAD

**Issue by lipkau** [lipkau/ol.modules#31]
before releasing [Alpha Milestone](https://github.com/lipkau/ol.modules/milestone/1) the following tasks must be performed:
* [ ] increment of module's _versions_
* [ ] ensure wiki documentations ip up-to-date
* [ ] upload updated screenshot in wiki documentation with alpha release
* [ ] ensure screenshot in wiki documentation only include modules that are part of the release
